/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_resultjs_free(a: number): void;
export function resultjs_n_cdr3(a: number, b: number): void;
export function resultjs_aa_cdr3(a: number, b: number): void;
export function resultjs_seq(a: number, b: number): void;
export function resultjs_full_seq(a: number, b: number): void;
export function resultjs_reconstructed_seq(a: number, b: number): void;
export function resultjs_aligned_v(a: number, b: number): void;
export function resultjs_aligned_j(a: number, b: number): void;
export function resultjs_v_name(a: number, b: number): void;
export function resultjs_j_name(a: number, b: number): void;
export function resultjs_pgen(a: number): number;
export function resultjs_likelihood(a: number): number;
export function resultjs_pos_start_cdr3(a: number): number;
export function resultjs_cdr3_pos_string(a: number, b: number): void;
export function wrappedmodel_initialize(): number;
export function wrappedmodel_load_model(a: number, b: number, c: number, d: number): number;
export function wrappedmodel_generate(a: number, b: number): void;
export function wrappedmodel_evaluate(a: number, b: number, c: number): void;
export function fetch_file(a: number, b: number): number;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function wasm_bindgen__convert__closures__invoke1_mut__h31b799c0ba683a3f(a: number, b: number, c: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__h0f6d768d0ffb232d(a: number, b: number, c: number, d: number): void;
